version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: translation-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - translation-network

    db:
        image: mysql:8.0
        container_name: translation-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - translation-network

    nginx:
        image: nginx:alpine
        container_name: translation-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - translation-network

networks:
    translation-network:
        driver: bridge

volumes:
    dbdata:
